---
name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  lint-github:
    name: Lint Code Base
    uses: hspaans/.github/.github/workflows/lint.yml@v3
